regs_module.v: implement TPM_ACCESS register
Dasharo/verilog-tpm-fifo-registers pull request #2
Opened 2023-05-04 19:10 UTC by krystian-hebel

Specification leaves some parts of the implementation to be defined by vendors. Assumptions made by this commit:

- Unset locality has lower priority than Locality 0.
- TPM_INT_* registers can be read from all localities (including no locality), but can be written just from active locality. There is one set of those registers aliased between all localities.
- Implementation makes it possible to set requestUse from Locality 4, wait for lower priority locality to relinquish control of the TPM and then have activeLocality set for Locality 4. Access to Locality 4 register space should be blocked by platform, so described case should be impossible to do in practice.

2023-05-19 11:04 UTC, miczyg1 requested changes
Besides the two comments I don't see any other issues

2023-05-19 11:04 UTC, miczyg1 commented on regs_tb.v
> +      read_b (locality_addr (1, i), tmp_reg[7:0]);
Wouldn't it be more wise to use locality 4 here? At least we would cover registers accessible in locality 4 only (`TPM_HASH_*`) ?

2023-05-19 11:04 UTC, miczyg1 commented on regs_tb.v
> +        read_b (locality_addr (1, i), tmp_reg[7:0]);
a/a

2023-05-23 09:51 UTC, krystian-hebel commented on regs_tb.v
> +      read_b (locality_addr (1, i), tmp_reg[7:0]);
Good point, changed.

2023-05-23 09:51 UTC, krystian-hebel commented on regs_tb.v
> +        read_b (locality_addr (1, i), tmp_reg[7:0]);
Changed.

2023-05-23 16:11 UTC, miczyg1 commented
@krystian-hebel I see the locality has been changed to 4 in the testbench. Does that not change the expected values at all?

2023-05-23 16:45 UTC, krystian-hebel commented
@miczyg1 no, all special registers in Locality 4 are read as FFs, just as they are for other localities. Additional blocking of access is implemented by host hardware (northbridge/PCH/whatever) so any read from Locality 4 should return FFs from the software's point of view, but this testbench operates few levels lower than that.

2023-05-23 16:50 UTC, miczyg1 approved these changes

2023-05-24 09:13 UTC, merged