Synth fix
Dasharo/verilog-tpm-fifo-registers pull request #5
Opened 2023-06-26 10:26 UTC by krystian-hebel

2023-06-26 13:03 UTC, krystian-hebel commented
Moving back to draft. For some reason `interrupt` port is driven as a constant 0...

2023-08-02 13:31 UTC, miczyg1 requested changes

2023-08-02 13:31 UTC, miczyg1 commented on regs_module.v
>                // TIS supported, CRB not supported, Locality 0 only
Now that I look at it, 0x21 here means TIS supported, CRB not supported, and 5 localities supported

2023-08-02 13:31 UTC, miczyg1 commented on regs_module.v
> +    interrupt <= globalIntEnable & |irq_num &
What does the notation `& |` mean? It looks like and or concatenated

2023-08-02 13:37 UTC, krystian-hebel commented on regs_module.v
>                // TIS supported, CRB not supported, Locality 0 only
Right, I've changed the value previously but not the comment, will fix.

2023-08-02 13:37 UTC, krystian-hebel commented on regs_module.v
> +    interrupt <= globalIntEnable & |irq_num &
This is [reduction operator](https://class.ece.uw.edu/cadta/verilog/reduction.html). All bits of `irq_num` are `or`ed together to produce one bit and the result is then `and`ed with `globalIntEnable`.

2023-08-02 14:14 UTC, krystian-hebel commented on regs_module.v
>                // TIS supported, CRB not supported, Locality 0 only
Fixed in https://github.com/Dasharo/verilog-tpm-fifo-registers/pull/5/commits/95fc170d551451c2e1b63b2bf09123db1b9503ae

2023-08-02 14:54 UTC, miczyg1 approved these changes

2023-08-02 14:54 UTC, merged